@startuml
skinparam NoteBackgroundColor white
hide empty description
state OUT_GAME
state restart as " "
state ifEnd <<choice>>
OUT_GAME -[#green]-> restart
note on link
 <b> Player request
 restart
 end note
restart -[#green]-> ifEnd
 note on link
  <b> System required
  "y" or "n" character
 end note
ifEnd -[#green]-> INIT
note on link
<b> Player provide
"y" character
end note
ifEnd --> EXIT
note on link
<b> Player provide
"n" character
end note
ifEnd --> OUT_GAME : [player provide wrong character]
INIT --> [*]
EXIT --> [*]
@enduml