@startuml

title Start
skinparam NoteBackgroundColor white
hide empty description
state INIT as "INIT"
state startedGame as " "
state numberOfPlayers as " "
state ifValidNumberOfPlayers <<choice>>
state showBoard as "Show Board"

[*] --> INIT
INIT -[#green]-> startedGame
note on link #white
  <b>Player request to
  start a new game
end note
startedGame -[#green]-> numberOfPlayers
note on link
  <b>System shows
  title required number of players
  <b>System requires
  number of players
  <b>System allows
  only numbers > 0
end note
numberOfPlayers -[#green]-> ifValidNumberOfPlayers
note on link
  <b>Player provides
  number of players
end note
ifValidNumberOfPlayers --> startedGame
note on link
  <b>System shows
  invalid numer of players
end note
ifValidNumberOfPlayers -[#green]-> showBoard
note on link
  <b>System shows
  board
end note
showBoard -[#green]-> IN_GAME
note on link
  <b>System allows
  start game
  <b>System requires
  player propose combination
end note

@enduml