@startuml
title Propose
skinparam NoteBackgroundColor white
hide empty description
state userRequiresCompareWord as " "
state showBoard as "Show Board"
state ifValidPropose <<choice>>
state ifEndGame <<choice>>

IN_GAME -[#green]-> userRequiresCompareWord
note on link #white
  <b>Player provide
  proposed characters
end note
userRequiresCompareWord -[#green]-> ifValidPropose
note on link #white
  <b>System requires
  player characters
  <b>System allows
  - only characters
  - length > 0
end note
ifValidPropose -[#green]-> showBoard : [valid input propose]
note on link
  <b>System shows
  board
  end note
ifValidPropose -up-> IN_GAME
note on link #white
  <b>System shows
 board
end note
note on link #white
  <b>System shows
  invalid input propose
end note
showBoard -[#green]-> ifEndGame
ifEndGame -up-> IN_GAME : [game not end]
ifEndGame -[#green]-> OUT_GAME : [lose or win]
note on link #white
  <b> System shows
  restart title
end note
@enduml