@startuml
Object ":Hanged" as Hanged
Object ":Turn" as Turn
Object ":StartController" as StartController
Object ":Logic" as Logic
Object ":Game" as Game
Object ":State" as State
Object ":Player" as Player
Object ":StartView" as StartView
Object ":SecretWord" as SecretWord
Object ":ProposedWord" as ProposedWord
Object ":StateValue.START" as StateValue



Hanged --> StartView
Hanged --> StartController
StartView ..> StartController
StartController o--> Logic
Logic *--> Game
Game *--> Turn
Game *--> State
Game *--> SecretWord
State --> StateValue
Turn *--> Player
note left: "puede haber varios objetos usuario"
Player --> ProposedWord
Game o--> ProposedWord

@enduml
