@startuml
package "main" {
class Hanged
}

package "views"{
abstract class View
    package "console" {
        class StartView
        class InGameView
    }
}

package "controllers"{
class Logic
enum SesionValue
abstract class Controller
class StartController
class ProposedWordController
class ProposedCharController
class EndController


}


package "models" {
abstract class Word
class ProposedChar
class ProposedWord
class SecretWord
class HangedPart
class Turn
class Player
}
Hanged *--> View
Hanged *--> Logic
Logic o--> Controller
View <|-- StartView
View <|-- InGameView

Controller <|-- StartController
Controller <|-- ProposedWordController
Controller <|-- ProposedCharController
Controller <|-- EndController

Logic o--> SesionValue
Word <|-- ProposedChar
Word <|-- ProposedWord
Word <|-- SecretWord



@enduml